create database ola_cab_booking;

use ola_cab_booking;
show tables;
describe bengaluru_ola_booking_data;
select *
from bengaluru_ola_booking_data;

-- CUSTOMER & BOOKING ANALYSIS --
-- 1. Identify customers who have completed the most bookings. What insights can you draw about their behavior? 
SELECT Customer_ID, COUNT(*) AS total_completed
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY Customer_ID
ORDER BY total_completed DESC
LIMIT 5;

-- 2. Find customers who have canceled more than 30% of their total bookings. What could be the reason for frequent cancellations? 
SELECT Customer_ID,
       SUM(CASE WHEN Booking_Status LIKE 'Cancelled%' THEN 1 ELSE 0 END) AS canceled,
       COUNT(*) AS total,
       ROUND((SUM(CASE WHEN Booking_Status LIKE 'Cancelled%' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS cancel_rate
FROM bengaluru_ola_booking_data
GROUP BY Customer_ID
HAVING cancel_rate > 30;

-- 3. Determine the busiest day of the week for bookings. How can the company optimize cab availability on peak days? 
SELECT DAYNAME(Date) AS day, COUNT(*) AS total_bookings
FROM bengaluru_ola_booking_data
GROUP BY day
ORDER BY total_bookings DESC;

-- REVENUE & BUSINESS METRICS --
-- 1. Calculate the total revenue generated by completed bookings in the last 6 months. How has the revenue trend changed over time? 
SELECT 
    DATE_FORMAT(date, '%Y-%m') AS month,
    SUM(CAST(Booking_Value AS DECIMAL(10,2))) AS total_revenue,
    COUNT(*) AS total_completed_bookings
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
  AND date >= DATE_SUB((SELECT MAX(date) FROM bengaluru_ola_booking_data), INTERVAL 6 MONTH)
GROUP BY DATE_FORMAT(date, '%Y-%m')
ORDER BY month ASC;
  
-- 2. Identify the top 3 most frequently traveled routes based on PickupLocation and DropoffLocation. Should the company allocate more cabs to these routes? 
SELECT Pickup_Location, Drop_Location, COUNT(*) AS trips
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY Pickup_Location, Drop_Location
ORDER BY trips DESC
LIMIT 3;

-- 3. Determine if higher-rated drivers tend to complete more trips and earn higher fares. Is there a direct correlation between driver ratings and earnings? 
SELECT Customer_ID,
       AVG(Driver_Ratings) AS avg_rating,
       SUM(Booking_Value) AS total_earnings,
       COUNT(*) AS trips
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY Customer_ID
ORDER BY avg_rating DESC;

-- OPERATIONAL EFFICIENCY  &  OPTIMIZATION --
-- 1. Analyze the average waiting time (difference between booking time and trip start time) for different pickup locations. How can this be optimized to reduce delays? 
SELECT Pickup_Location,
       AVG(Avg_VTAT) AS avg_vehicle_wait,
       AVG(Avg_CTAT) AS avg_customer_wait
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY Pickup_Location
ORDER BY avg_vehicle_wait DESC;

-- 2. Identify the most common reasons for trip cancellations from customer feedback. What actions can be taken to reduce cancellations? 
SELECT Reason_for_Cancelling_by_Customer, COUNT(*) AS cnt
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Cancelled by Customer'
-- AND Reason_for_cancelling_by_Customer IS NOT NULL
GROUP BY Reason_for_Cancelling_by_Customer
ORDER BY cnt DESC;
-- Limit 10;



-- 3. Find out whether shorter trips (low-distance) contribute significantly to revenue. Should the company encourage more short-distance rides? 
SELECT CASE WHEN Ride_Distance < 5 THEN 'Short Trip' ELSE 'Long Trip' END AS trip_type,
       SUM(Booking_Value) AS total_revenue
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY trip_type;

-- COMPARATIVE & PREDICTIVE ANALYSIS --
-- 1. Compare the revenue generated from 'Sedan' and 'SUV' cabs. Should the company invest more in a particular vehicle type? 
SELECT Vehicle_Type, SUM(Booking_Value) AS total_revenue
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Cancelled by customer'
  AND Vehicle_Type IN ('Prime Sedan','Prime SUV')
GROUP BY Vehicle_Type;

-- 2. Predict which customers are likely to stop using the service based on their last booking date and frequency of rides. How can customer retention be improved? 
SELECT Customer_ID, MAX(Date) AS last_booking
FROM bengaluru_ola_booking_data
GROUP BY Customer_ID
HAVING last_booking < DATE_SUB(CURDATE(), INTERVAL 3 MONTH);

-- 3. Analyze whether weekend bookings differ significantly from weekday bookings. Should the company introduce dynamic pricing based on demand? 
SELECT CASE 
           WHEN DAYOFWEEK(Date) IN (1,7) THEN 'Weekend'
           ELSE 'Weekday'
       END AS day_type,
       COUNT(*) AS total_bookings
FROM bengaluru_ola_booking_data
GROUP BY day_type;







SELECT Customer_ID, AVG(Driver_Ratings) AS avg_rating
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
  AND Date >= DATE_SUB(CURDATE(), INTERVAL 3 MONTH)
GROUP BY Customer_ID
HAVING avg_rating < 3.0;

SELECT Customer_ID, SUM(Ride_Distance) AS total_distance
FROM bengaluru_ola_booking_data
WHERE Booking_Status = 'Success'
GROUP BY Customer_ID
ORDER BY total_distance DESC
LIMIT 5;

SELECT Customer_ID,
       SUM(CASE WHEN Booking_Status LIKE 'Cancelled%' THEN 1 ELSE 0 END) AS canceled,
       COUNT(*) AS total,
       ROUND((SUM(CASE WHEN Booking_Status LIKE 'Cancelled%' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS cancel_rate
FROM bengaluru_ola_booking_data
GROUP BY Customer_ID
HAVING cancel_rate > 30;